version: '3.8'

services:
  nextjs:
    image: node:18.3.0-alpine3.14
    ports:
      - 3000:3000
    tty: true
    volumes:
      - ./front/demo:/app/demo
    working_dir: /app/demo
    environment:
      - NODE_ENV=development
    user: node
